version: '3'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: pintoss_local
      POSTGRES_USER: pintoss_local
      POSTGRES_PASSWORD: pintoss_local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  redis:
#    image: redis:alpine
#    command: redis-server --port 6379
#    labels:
#      - "name=redis"
#      - "mode=standalone"
#    ports:
#      - 6379:6379

volumes:
  postgres_data:
