
spring:
  messages:
    encoding: EUC-KR
  datasource:
    url: jdbc:mariadb://pintossmall2.cafe24.com:3306/pintossmall2?serverTimezone=UTC&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    username: pintossmall2
    password: cho459800
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
  profiles:
    include: oauth,pay,coolsm
  config:
    import: optional:file:.env[.properties]
  mail:
    host: smtp.naver.com
    port: 465
    username: c0810@naver.com
    password: 1234
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  thymeleaf:
    cache: false
    check-template-location: true
    mode: HTML
    prefix: file:src/main/resources/templates/
    suffix: .html
    encoding: EUC-KR


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
server:
  port: 88