spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pintoss
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  profiles:
    include: oauth
  config:
    import: optional:file:.env[.properties]