spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/pintossmall2?serverTimezone=UTC&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    username: pintossmall2
    password: cho459800
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
  profiles:
    include: oauth, aws
  config:
    import: optional:file:.env[.properties]
  mail:
    host: smtp.naver.com
    port: 465
    username: c0810@naver.com
    password: 1234
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
