spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 819428ebda4254458e971e3d9bb89822
            client-secret: ySzHWh5333VN2ktUNVaqvrZPnvVSZZoX
            redirect-uri: https://pintossmall2.com/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - account_email
            client-name: kakao

          naver:
            client-id: ntP6_ogtZLkuD6J774IT
            client-secret: 9cIj0Lo1b_
            redirect-uri: https://pintossmall2.com/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - email
            client-name: naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  config:
    import: optional:file:.env[.properties]