spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pintoss
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  profiles:
    include: oauth
  config:
    import: optional:file:.env[.properties]
  mail:
    host: smtp.naver.com
    port: 465
    username: c0810@naver.com
    password: ${OWNER_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
